% 'C:\Users\conwayr2\OneDrive\RachelConway\SweepProfileEffects\Spice\SpEED_Demon.net'
% C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe

function raw_data = Variable_netlist_Fast(PUWULstring,tend,Ni,Te,Rc,Cc)


% Write netlist to file name 
filename = strcat('general_SPICE_netlist');
filenamewithpath = strcat('./Accessory_Files/general_SPICE_netlist.net');
netlist = [filenamewithpath];
code = [';Comment to Initialize\r\n'...
        '; Define constants \r\n'...
        '.PARAM Qe = 1.602e-19\r\n'...
        '.PARAM Kb = 1.381e-23\r\n'...
        '.PARAM Pix = 3.1415926\r\n'...
        '.PARAM Me = 9.109e-31\r\n'...
        '.PARAM Mi = 1.673e-27\r\n'...
        '.PARAM Mion  = 16\r\n'...
        '.PARAM Te  = TESTRING\r\n'...
        '.PARAM Ti  = Te\r\n'...
        '.PARAM N   = NISTRING\r\n'...
        '.PARAM res = RCSTRING\r\n'...
        '.PARAM cap = CCSTRING\r\n'...  
        '; Payload Surface\r\n'...
        'Xsurface 4 0 OMLEquation PARAMS: A=100.1493, ebeta=0.5,ionbeta = 0.5\r\n'...
        '; Voltage Applied to SLP\r\n'...
        'Vdac 1 4 PWL(PUWULstring)\r\n'...  
        ';SLP Contamination Layer\r\n'...
        'R 1 3 {res}\r\n'...  
        'C 1 3 {cap}\r\n'...  
        '; Sweeping Langmuir Probe\r\n'...
        'Xlangmuir 3 0 OMLEquation PARAMS: A=0.00052339, ebeta = 0.8,ionbeta = 0.8\r\n'...
        '.OP\r\n'...
        '.TRAN 1e-2 TEND 0 1e-3\r\n'...
        '; Voltage Dependent Current Source (OML Theory)\r\n'...'
        '.subckt OMLEquation a b PARAMS: Ne={N}, Ni={N}, M={Mion},ebeta = 0.5,ionbeta = 0.5\r\n'...
        'Gi a b VALUE = { IF ( V(a) <= V(b),   -Qe * Ni * A * sqrt( (Kb * Ti / (2 * Pix * Mi * M))) * (1 - (Qe * V(a) / (Kb * Ti)))^ionbeta,\r\n'...
        '+ -Qe * Ni * A * sqrt( Kb * Te / (2 * Pi * Mi * M)) * exp( -Qe * V(a) / (Kb * Ti)))}\r\n'...
        'Ge a b VALUE = { IF ( V(a) >= V(b),  Qe * Ne * A * sqrt( (Kb * Te / (2 * Pix * Me))) * (1 + (Qe * V(a) / (Kb * Te)))^ebeta,\r\n'...
        '+  Qe * Ne * A * sqrt( Kb * Te / (2 * Pi * Me)) * exp( Qe * V(a) / (Kb * Te)))}\r\n'...
        'R a b 10000000T\r\n'...
        '.ends\r\n'...
        '.END\r\n'];
    % Replace strings with user inputs
    code = strrep(code,'PUWULstring',PUWULstring);
    code = strrep(code,'TEND',num2str(tend));
    code = strrep(code,'RCSTRING',num2str(Rc));
    code = strrep(code,'CCSTRING',num2str(Cc));
    code = strrep(code,'TESTRING',num2str(Te));
    code = strrep(code,'NISTRING',num2str(Ni));
    
    % Write script to netlist file
    [fid message]  = fopen(netlist,'w+');
    if fid < 0
        error('Failed to open myfile because: %s', message);
    end
    fprintf(fid,code);
    fid = fclose(fid);
    
    % Write .bat file
    [fid message]  = fopen(strcat(pwd,'/Accessory_Files/LTSpice_call_1','.bat'),'w+');
    fprintf(fid,['\"%s\" -b -RUN %s'],'C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe',strcat(pwd,'\Accessory_Files\general_SPICE_netlist.net'));
    fid = fclose(fid);
    % Run SPICE netlist
    dos(strcat(pwd,'\Accessory_Files\LTSpice_call_1','.bat'));
    
    % Save output
    raw_data = LTspice2Matlab(strcat(pwd,'/Accessory_Files/',filename,'.raw'));
end